
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdqtckrgcofpdyrhrrqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkcXRja3JnY29mcGR5cmhycnFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODc3MDIsImV4cCI6MjA1OTI2MzcwMn0.myCyj0wnq94QpoAO2K-WH_9BwPwJBm-Rsph9STp9f8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Configure with localStorage and session persistence
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
