
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdqtckrgcofpdyrhrrqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkcXRja3JnY29mcGR5cmhycnFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODc3MDIsImV4cCI6MjA1OTI2MzcwMn0.myCyj0wnq94QpoAO2K-WH_9BwPwJBm-Rsph9STp9f8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Configure with localStorage and session persistence
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Types for address_settings table (until types.ts gets updated)
export interface AddressSettings {
  id?: string;
  sender_name: string;
  sender_address: string;
  sender_city: string;
  sender_country: string;
  sender_postal_code: string;
  receiver_name: string;
  receiver_address: string;
  receiver_city: string;
  receiver_country: string;
  receiver_postal_code: string;
  created_at?: string;
  updated_at?: string;
}

// Type-safe function to access address_settings table
export const getAddressSettingsTable = () => {
  // Use a more direct approach that bypasses strict typing temporarily
  return supabase.from('address_settings');
};
